// A stable, canonical base URL for links Supabase emails out (signup
// confirmation, resend confirmation, password reset) — see
// usersService.js's registerPatient/resendConfirmationEmail and
// AuthContext.jsx's requestPasswordReset, all three of which need one.
//
// Every one of those previously used `window.location.origin` directly,
// which bakes in whatever URL happened to be open in the browser AT THE
// MOMENT the person triggered the action — not a fixed, known-working
// address. That's fragile in a very concrete way for local development:
// this project's .env.local was generated by the Vercel CLI, meaning
// registration has very likely been tested at some point via
// `vercel dev` (which defaults to port 3000) rather than the normal
// `npm run dev` (Vite, port 5173) most day-to-day work actually runs
// on. A confirmation email sent while `vercel dev` happened to be
// running gets `http://localhost:3000` permanently embedded in its
// link — which then fails with ERR_CONNECTION_REFUSED the moment
// that's clicked later, once only the normal dev server (a different
// port) is running. The exact same risk exists in production too, just
// less commonly hit — any origin variation (a preview deployment URL,
// a staging subdomain, etc.) would get baked in the same way.
//
// VITE_APP_URL lets you pin this to one deliberate, always-reachable
// address (e.g. your real production domain, or explicitly
// http://localhost:5173 for local work) regardless of which local
// server happens to be open when someone registers or resets their
// password. Falls back to window.location.origin when unset, so this
// still works with zero setup for anyone who only ever uses one
// consistent URL — the fallback is the same behavior as before, just
// no longer the ONLY option.
export function getAppUrl() {
  return import.meta.env.VITE_APP_URL || window.location.origin
}