// A stable, canonical base URL for links Supabase emails out (signup
// confirmation, resend confirmation, password reset) — see
// usersService.js's registerPatient/resendConfirmationEmail and
// AuthContext.jsx's requestPasswordReset, all three of which need one.
//
// Every one of those previously used `window.location.origin` directly,
// which bakes in whatever URL happened to be open in the browser AT THE
// MOMENT the person triggered the action — not a fixed, known-working
// address. That's fragile in a very concrete way for local development:
// this project's .env.local was generated by the Vercel CLI, meaning
// registration has very likely been tested at some point via
// `vercel dev` (which defaults to port 3000) rather than the normal
// `npm run dev` (Vite, port 5173) most day-to-day work actually runs
// on. A confirmation email sent while `vercel dev` happened to be
// running gets `http://localhost:3000` permanently embedded in its
// link — which then fails with ERR_CONNECTION_REFUSED the moment
// that's clicked later, once only the normal dev server (a different
// port) is running. The exact same risk exists in production too, just
// less commonly hit — any origin variation (a preview deployment URL,
// a staging subdomain, etc.) would get baked in the same way.
//
// VITE_APP_URL lets you pin this to one deliberate, always-reachable
// address (e.g. your real production domain, or explicitly
// http://localhost:5173 for local work) regardless of which local
// server happens to be open when someone registers or resets their
// password. Falls back to window.location.origin when unset, so this
// still works with zero setup for anyone who only ever uses one
// consistent URL — the fallback is the same behavior as before, just
// no longer the ONLY option.
export function getAppUrl() {
  const configured = (import.meta.env.VITE_APP_URL || '').trim()
  const isConfiguredLocalhost = /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/?$/i.test(configured)
  const isRunningOnLocalhost = /^(localhost|127\.0\.0\.1)$/i.test(window.location.hostname)

  // Guards against the exact failure this whole file exists to prevent,
  // just from the opposite direction: VITE_APP_URL pins the redirect to
  // one deliberate address, but if that address is localhost and this
  // code is actually running somewhere that is NOT localhost (a real
  // deployment — Vercel, a custom domain, a staging URL), trusting it
  // would silently bake an unreachable http://localhost:... link into
  // every confirmation/reset email sent from production. That's a very
  // plausible real misconfiguration to end up with, not a hypothetical
  // one: VITE_APP_URL=http://localhost:3000 copy-pasted into Vercel's
  // dashboard env vars alongside the rest of a local .env file (or left
  // over from testing locally with `vercel dev`) would do exactly this
  // otherwise. In that specific case, fall through to
  // window.location.origin instead — the real, currently-running
  // address — rather than trusting the stale configured value.
  if (isConfiguredLocalhost && !isRunningOnLocalhost) {
    return window.location.origin
  }

  return configured || window.location.origin
}