// Ported verbatim from the legacy Print.execute() — opens a real popup
// window, writes formatted print HTML into it, and triggers window.print().
// No print library needed; this is just string building + the browser API.
export function openPrintWindow(title, headers, rows, subtitle, ts) {
  const win = window.open('', '_blank', 'width=900,height=700')
  if (!win) return false // popup blocked

  const thHTML = headers.map((h) => `<th>${h}</th>`).join('')
  const tbHTML = rows.map((r) => `<tr>${r.map((c) => `<td>${c || '—'}</td>`).join('')}</tr>`).join('')
  const html = `<!DOCTYPE html><html style="color-scheme:light"><head><meta name="color-scheme" content="light"><title>${title}</title>
    <style>
      html,body{color-scheme:light!important}
      body{font-family:Segoe UI,sans-serif;padding:24px;color:#1A1310;background:#fff}
      h1{font-size:18px;color:#1E7B5E;margin-bottom:4px}
      .meta{font-size:11px;color:#555;padding-bottom:12px;border-bottom:2px solid #1E7B5E;margin-bottom:16px}
      table{width:100%;border-collapse:collapse;font-size:11px}
      th{background:#E3F4EF;color:#1E7B5E;padding:8px;text-align:left;font-size:10px;text-transform:uppercase;border:1px solid #ddd}
      td{padding:7px 8px;border:1px solid #eee;color:#1A1310}tr:nth-child(even) td{background:#f8f9ff}
      .footer{margin-top:20px;font-size:10px;color:#777;text-align:center;border-top:1px solid #eee;padding-top:8px}
      @media print{
        html,body{color-scheme:light!important;background:#fff!important;color:#000!important}
        *{color:#000!important}
        h1{color:#1E7B5E!important}
        th{background:#E3F4EF!important;color:#1E7B5E!important}
        td{color:#000!important;background:#fff!important}
        tr:nth-child(even) td{background:#f8f9ff!important}
      }
    </style></head><body>
    <h1>${title}</h1>
    <div class="meta">${subtitle || 'Capstone Prototype'}&nbsp;|&nbsp;Generated: ${ts}&nbsp;|&nbsp;${rows.length} record(s)</div>
    <table><thead><tr>${thHTML}</tr></thead><tbody>${tbHTML}</tbody></table>
    <div class="footer">Generated by Capstone Prototype Clinic Services System. For official use only.</div>
    </body></html>`

  win.document.write(html)
  win.document.close()
  setTimeout(() => win.print(), 500)
  return true
}
