-- New, genuinely separate ID field for staff/admin accounts — NOT the
-- same mechanism as patients' student_number (patient_profiles), by
-- design. Patients' student_number is a real, externally-assigned,
-- admin-editable value (their actual school-issued number). This field
-- is the opposite on every axis: system-generated, read-only in the
-- UI, and purely random with no predictable pattern (no timestamp
-- component, unlike school_id_barcode) — a student number is often
-- sequential/guessable by nature of how schools assign them, which is
-- an acceptable tradeoff for identifying a patient but not appropriate
-- for staff/admin accounts, which hold materially more privileged
-- access to the system.

ALTER TABLE staff_profiles
  ADD COLUMN IF NOT EXISTS staff_id_number VARCHAR(30) UNIQUE;

COMMENT ON COLUMN staff_profiles.staff_id_number IS
  'System-generated, read-only identifier for staff/admin accounts — deliberately NOT the same mechanism as patients'' student_number (see this migration''s header comment for the full reasoning). Generated by generateStaffId() in src/lib/schoolId.js.';

-- Backfill: every existing staff/admin account that predates this
-- column gets one now. Purely random (no seed from user_id or time),
-- generated directly in SQL via gen_random_uuid() — Supabase projects
-- have pgcrypto enabled by default, which provides this. Safe to
-- re-run: only touches rows where staff_id_number IS NULL.
UPDATE staff_profiles
SET staff_id_number = 'STF-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10))
WHERE staff_id_number IS NULL;